build:
    version: @project.version@
spring:
  sql:
    init:
      mode: always
      data-locations: optional:classpath*:data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:resource:/bd